"""Build a local, self-contained geometry review document (images alongside)."""
from pathlib import Path
import json
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'design/review'
data=json.loads((OUT/'layout-options.json').read_text())
html='''<!doctype html>
<html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Tofu — first design review</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#fbf8f2;color:#302d28;font:16px/1.55 system-ui,sans-serif}main{max-width:1280px;margin:auto;padding:40px}header{border-bottom:1px solid #dcd6ca;padding-bottom:24px;margin-bottom:28px}.eyebrow{font-size:12px;letter-spacing:2px;color:#526b60}h1{font-size:42px;line-height:1.15;margin:10px 0}h2{font-size:24px;margin:0 0 12px}p{max-width:800px}small,.muted{color:#6c665d}.layout{display:grid;grid-template-columns:minmax(0,1.5fr) minmax(300px,1fr);gap:36px}button{font:inherit;border:1px solid #bfb8ab;background:transparent;border-radius:30px;padding:10px 16px;cursor:pointer}button[aria-pressed=true]{background:#304c40;color:white;border-color:#304c40}.choices{display:flex;flex-wrap:wrap;gap:8px;margin:0 0 20px}.drawing{width:100%;max-height:570px}.drawing path{cursor:pointer}.drawing path:hover,.drawing path:focus{stroke:#1f4e3e;stroke-width:1.2;outline:none}.metric{font-size:36px;line-height:1.2;margin-top:18px}.caption{font-size:13px}.line{border-top:1px solid #dcd6ca;padding-top:22px;margin-top:22px}.image{width:100%;display:block}a{color:#2a6049}section{margin-bottom:38px}.badge{font-size:12px;letter-spacing:1px;text-transform:uppercase;color:#895849}.selected{min-height:48px}label{display:block;margin-top:20px}@media(max-width:850px){main{padding:22px}.layout{grid-template-columns:1fr}h1{font-size:32px}}
</style>
<main><header><div class="eyebrow">TOFU / DESIGN NOTE 01</div><h1>Bigger dogs. A better press.</h1><p>First silhouette studies for a 120 × 100 mm sheet. Compare complete shapes and the tofu left around them before choosing a design direction.</p><span class="badge">Exploration · no final cutter selected</span></header>
<section><div class="choices" aria-label="Silhouette option"><button data-i="0" aria-pressed="false">A · Interlocking</button><button data-i="1" aria-pressed="true">B · Full-body puppies</button><button data-i="2" aria-pressed="false">C · Puppy heads</button></div><div class="layout"><div><svg id="layout" class="drawing" viewBox="-5 -6 130 115" role="img" aria-label="Selected cutting layout in a 120 by 100 millimetre rectangle"></svg><p class="caption">Tan: complete silhouettes · pink: fragments · gray: area outside the openings. Click a shape for its area. No decorative facial details are implied.</p></div><aside><h2 id="name"></h2><p id="note"></p><div class="metric" id="count"></div><div class="muted">complete silhouettes</div><div class="metric" id="coverage"></div><div class="muted">of the sheet inside complete shapes</div><p id="outside"></p><p class="selected" id="selected" aria-live="polite">Select a piece to inspect its area.</p><label><input id="remainder" type="checkbox"> Emphasize area outside complete shapes</label><p class="line caption">These are outline-area comparisons, not food-waste measurements. B and C are nesting studies, not zero-scrap tessellations; blade thickness is not yet included. None meets the low-waste goal yet.</p></aside></div></section>
<section class="line"><div class="layout"><div><h2>A comfortable place to press</h2><img class="image" src="grip-study.png" alt="CadQuery rendering of the perimeter cutting rim with broad oval palm pads on both sides"></div><aside><span class="badge">Frame-only CadQuery study</span><p>Broad oval palm pads, rounded upper edges, and 28 mm of clearance beneath the pressing surfaces.</p><p>The perimeter wall tapers from 1.6 mm to a nominal 0.30 mm edge over 4 mm. Overall height: 36 mm.</p><p>Dog blades and upper supports follow layout selection. Printability, comfort, and cutting performance are untested.</p><p><a href="grip-study.step">Frame STEP</a> · <a href="frame-only-study.stl">Frame-only STL</a><br><small>This STL is not a functional cutter.</small></p></aside></div></section>
<section class="line"><h2>What the original STL tells us</h2><p><strong>117.37 × 99.32 × 10.00 mm</strong> overall; approximately <strong>101.39 × 84.08 mm</strong> across the internal opening envelope. The redesign uses your stated 120 × 100 mm target.</p><p>The 25 openings include nine visually complete dogs, one shortened dog, and fifteen other fragments. Internal contours match at three sampled heights, consistent with untapered walls. A 10 mm tall tool cannot pass through the intended 25 mm tofu sheet.</p><details><summary>Original concept art and measured cross-section</summary><img class="image" src="../../big_dog_render.png" alt="Original dog cutter concept art"><img class="image" src="prototype-section.png" alt="Measured prototype cross-section with numbered openings"></details><p><a href="../REVIEW.md">Full review notes</a> · <a href="layout-comparison.svg">Comparison drawing</a> · <a href="prototype-audit.json">Measurements</a></p></section></main>
<script>
const options=__DATA__;let current=1;const svg=document.getElementById('layout');const ns='http://www.w3.org/2000/svg';
function draw(){const o=options[current],emphasis=document.getElementById('remainder').checked;svg.replaceChildren();const rect=document.createElementNS(ns,'rect');for(const [k,v] of Object.entries({x:0,y:0,width:120,height:100,fill:emphasis?'#d68d80':'#ebe6dd',stroke:'#8d8477','stroke-width':.4}))rect.setAttribute(k,v);svg.append(rect);
o.shapes.forEach((s,i)=>{let p=document.createElementNS(ns,'path');p.setAttribute('d','M'+s.points.map(a=>a.join(',')).join('L')+'Z');p.setAttribute('fill',s.complete?(emphasis?'#fbf8f2':['#edc790','#dcaf79','#efd5ab'][i%3]):'#eab0a6');p.setAttribute('stroke','#82715a');p.setAttribute('stroke-width','.3');p.setAttribute('tabindex','0');p.setAttribute('role','button');p.setAttribute('aria-label','Piece '+(i+1)+', '+(s.complete?'complete silhouette':'fragment')+', '+s.area_mm2+' square millimetres');let t=document.createElementNS(ns,'title');t.textContent=p.getAttribute('aria-label');p.append(t);const select=()=>document.getElementById('selected').textContent='Piece '+(i+1)+' · '+(s.complete?'complete silhouette':'fragment')+' · '+s.area_mm2+' mm²';p.onclick=select;p.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select()}};svg.append(p)});
let label=document.createElementNS(ns,'text');label.setAttribute('x','60');label.setAttribute('y','107');label.setAttribute('text-anchor','middle');label.setAttribute('font-size','3');label.textContent='120 × 100 mm';svg.append(label);
document.getElementById('name').textContent=o.title;document.getElementById('note').textContent=o.note;document.getElementById('count').textContent=o.complete_shapes;document.getElementById('coverage').textContent=o.complete_shape_area_percent+'%';document.getElementById('outside').textContent=o.other_area_percent+'% remains outside complete silhouettes.';document.querySelectorAll('[data-i]').forEach(b=>b.setAttribute('aria-pressed',Number(b.dataset.i)===current));}
document.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>{current=Number(b.dataset.i);document.getElementById('selected').textContent='Select a piece to inspect its area.';draw()});document.getElementById('remainder').onchange=draw;draw();
</script></html>'''
(OUT/'index.html').write_text(html.replace('__DATA__',json.dumps(data)))
print(OUT/'index.html')
