"""Local review document for the corrected side-profile studies."""
from pathlib import Path
import json
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'design/profile-review'
data=json.loads((OUT/'profiles.json').read_text())
html='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Tofu — reference-led profile study</title>
<style>*{box-sizing:border-box}body{margin:0;background:#faf7f1;color:#332f28;font:16px/1.5 system-ui,sans-serif}main{max-width:1360px;margin:auto;padding:36px}header{border-bottom:1px solid #d6cfc2;padding-bottom:20px;margin-bottom:26px}h1{font-size:38px;line-height:1.2;margin:8px 0}h2{font-size:18px;margin:0 0 12px}p{max-width:870px}.eyebrow{font-size:12px;letter-spacing:2px;color:#676558}.choices{display:flex;gap:10px;flex-wrap:wrap;margin:22px 0}button{font:inherit;border:1px solid #bfb5a4;border-radius:25px;padding:9px 17px;background:transparent;cursor:pointer}button[aria-pressed=true]{background:#3c5143;color:white;border-color:#3c5143}.layout{display:grid;grid-template-columns:250px minmax(0,1fr) 215px;gap:30px;align-items:start}.reference{width:100%;display:block}.muted{color:#70685c;font-size:14px}.drawing{width:100%;display:block;max-height:570px}.drawing path[role=button]{cursor:pointer}.drawing path[role=button]:hover,.drawing path[role=button]:focus{stroke:#214f39;stroke-width:.8;outline:none}.isolated{width:100%;height:220px}.line{border-top:1px solid #d6cfc2;margin-top:24px;padding-top:18px}.stat{font-size:28px}.caption{font-size:13px;color:#70685c}.notice{border-left:3px solid #b08a54;padding-left:16px}a{color:#2c5b43}footer{margin-top:28px}#piece{min-height:48px}@media(max-width:1050px){.layout{grid-template-columns:180px minmax(0,1fr)}.piece-panel{grid-column:2}.isolated{max-width:230px}}@media(max-width:650px){main{padding:20px}.layout{display:block}.reference{max-width:220px;margin-bottom:20px}.piece-panel{margin-top:20px}h1{font-size:30px}}</style>
<main><header><div class="eyebrow">TOFU / CORRECTED DIRECTION</div><h1>Side-profile dogs. Shared cutting lines.</h1><p>The original illustration is the reference. Alternating mirrored dogs fit head-to-legs, with no empty channels between neighboring shapes.</p></header>
<div class="choices"><button data-i="0" aria-pressed="true">A · 3 across × 2 rows</button><button data-i="1" aria-pressed="false">B · Longer dogs, 2 across × 3 rows</button></div>
<div class="layout"><aside><h2>Your original reference</h2><img class="reference" src="../original-tessellation-reference.jpeg" alt="User-supplied original illustration of alternating dog profiles tessellating in rows"><p class="caption">Eyes, ears, and color are illustration details. The proposed cutting outlines below do not rely on those marks.</p></aside><section><h2 id="title"></h2><svg class="drawing" id="drawing" viewBox="-2 -2 124 110" aria-label="Rectangular dog cutting layout" role="group"></svg><p class="caption">Tan = six complete profiles. Gray = remaining perimeter pieces. Adjacent perimeter scraps are merged to avoid unnecessary cuts.</p></section><aside class="piece-panel"><h2>Actual cut silhouette</h2><svg class="isolated" id="isolated" aria-label="Isolated dog profile without illustrative details" role="img"></svg><p class="caption">Plain outline, no eyes or ear drawing. Click a tan dog to inspect it.</p><p id="piece" aria-live="polite"></p><div class="line"><div class="stat" id="coverage"></div><div class="muted">of the sheet in whole dogs</div><p id="border"></p></div></aside></div>
<section class="line notice"><strong>The perimeter is still unresolved.</strong><p>These are shared-edge profile studies, not a finished cutting layout. Roughly one-third of the rectangle remains in edge pieces, with a small corner offcut in B. Zero gaps between dogs does not mean zero waste. The next layout pass must improve those boundaries while preserving recognizable dogs.</p><p class="caption">Measurements use zero-width cutting lines. Blade thickness, physical release, and cut quality are not simulated here. No new production STL is implied by this drawing.</p></section><footer><a href="profile-comparison.svg">Compare both layouts</a> · <a href="../PROFILE_REVIEW.md">Design notes</a> · <a href="profiles.json">Geometry and measurements</a></footer></main>
<script>
const options=__DATA__;let selected=0;const ns='http://www.w3.org/2000/svg';const root=document.getElementById('drawing');
function path(s){const p=document.createElementNS(ns,'path');p.setAttribute('d','M'+s.points.map(a=>a.join(',')).join('L')+'Z');return p}
function isolate(s,i){const svg=document.getElementById('isolated');svg.replaceChildren();let p=path(s);p.setAttribute('fill','#d4a36d');p.setAttribute('stroke','#665340');p.setAttribute('stroke-width','.45');svg.append(p);let xs=s.points.map(v=>v[0]),ys=s.points.map(v=>v[1]);const a=Math.min(...xs),b=Math.min(...ys),w=Math.max(...xs)-a,h=Math.max(...ys)-b;svg.setAttribute('viewBox',[a-3,b-3,w+6,h+6].join(' '));document.getElementById('piece').textContent='Dog '+i+' · '+w.toFixed(1)+' × '+h.toFixed(1)+' mm · '+s.area_mm2.toFixed(0)+' mm²';}
function draw(){const o=options[selected];root.replaceChildren();let dogIndex=0;let first=null;o.pieces.forEach(s=>{let p=path(s);p.setAttribute('fill',s.complete?['#dcaf78','#efc58c','#c59761'][dogIndex%3]:'#e4dfd6');p.setAttribute('stroke','#6c5d48');p.setAttribute('stroke-width','.24');if(s.complete){const index=++dogIndex;p.setAttribute('role','button');p.setAttribute('tabindex','0');p.setAttribute('aria-label','Inspect dog '+index);p.onclick=()=>isolate(s,index);p.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();isolate(s,index)}};if(!first)first=s;}root.append(p)});let t=document.createElementNS(ns,'text');t.setAttribute('x','60');t.setAttribute('y','106');t.setAttribute('text-anchor','middle');t.setAttribute('font-size','3');t.textContent='120 × 100 mm';root.append(t);document.getElementById('title').textContent=o.title;document.getElementById('coverage').textContent=o.complete_area_percent+'%';document.getElementById('border').textContent=o.boundary_area_percent+'% in '+o.perimeter_regions+' perimeter regions.';document.querySelectorAll('[data-i]').forEach(b=>b.setAttribute('aria-pressed',Number(b.dataset.i)===selected));isolate(first,1);}
document.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>{selected=Number(b.dataset.i);draw()});draw();
</script></html>'''
(OUT/'index.html').write_text(html.replace('__DATA__',json.dumps(data)))
